# Generated by Django 4.2.5 on 2023-10-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_genre_remove_game_genre_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_status',
            field=models.CharField(choices=[('Released', 'Released'), ('In Development', 'In Development'), ('On Hold', 'On Hold')], default='In Development', max_length=20),
        ),
    ]
