# Generated by Django 4.2.5 on 2023-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_release_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
    ]
