# Generated by Django 4.1.4 on 2023-11-08 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_game_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='faved_by',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
