# Generated by Django 4.1.4 on 2023-11-09 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_game_faved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='faved_by',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, to='game.genre'),
        ),
    ]
