# Generated by Django 4.2.7 on 2023-11-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_faved_by_alter_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_image', models.ImageField(upload_to='images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
