# Generated by Django 4.2.5 on 2023-12-10 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_devpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.devpost')),
            ],
        ),
        migrations.AddField(
            model_name='devpost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='dev_post_images', to='game.devpostimage'),
        ),
    ]
