# Generated by Django 4.2.5 on 2023-12-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_devpostimage_devpost_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devpost',
            name='images',
        ),
        migrations.DeleteModel(
            name='DevPostImage',
        ),
    ]
