# Generated by Django 4.2.5 on 2023-12-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_comment'),
        ('game', '0012_remove_devpost_images_delete_devpostimage'),
    ]

    operations = [
    ]
